### ISSUE TITLE
Milestone 2 feedback:

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1046#1]
Must fix: 

- [ ]  You should have 2 separate sections for tasks 4 and 5. Task 4 is an EDA that does not aim to answer any specific research question, instead it aims to explore the data. Task 5 on the other hand is when you do in depth analysis in order to answer research questions.
- [ ] Add more in depth research questions and analysis.
- [ ] Include more in your EDA.
- [ ] You need to call the functions from the project file when you do analysis.
